module.exports = {
  rules: {
    'no-descending-specificity': true,
    'declaration-block-no-duplicate-custom-properties': true,
    'declaration-block-no-duplicate-properties': true,
    'font-family-no-duplicate-names': true,
    'keyframe-block-no-duplicate-selectors': true,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'block-no-empty': true,
    'comment-no-empty': true,
    'no-empty-source': null,
    'color-no-invalid-hex': true,
    'function-calc-no-unspaced-operator': true,
    'keyframe-declaration-no-important': true,
    'media-query-no-invalid': true,
    'named-grid-areas-no-invalid': true,
    'named-grid-areas-no-invalid': null,
    'no-invalid-position-at-import-rule': null,
    'string-no-newline': null,
    'no-irregular-whitespace': null,
    'custom-property-no-missing-var-function': true,
    'font-family-no-missing-generic-family-keyword': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'selector-anb-no-unmatchable': true,
    'annotation-no-unknown': true,
    'at-rule-no-unknown': true,
    'declaration-property-value-no-unknown': true,
    'function-no-unknown': true,
    'media-feature-name-no-unknown': true,
    'media-feature-name-value-no-unknown': true,
    'no-unknown-animations': true,
    'no-unknown-custom-media': true,
    'no-unknown-custom-properties': null,
    'property-no-unknown': true,
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'unit-no-unknown': true,
    'at-rule-empty-line-before': 'always',
    'at-rule-no-vendor-prefix': true,
    'color-hex-alpha': 'never',
    'color-named': 'never',
    'color-no-hex': null,
    'declaration-no-important': true,
    'length-zero-no-unit': true,
    'selector-no-qualifying-type': null,
    'selector-no-vendor-prefix': true,
    'value-no-vendor-prefix': true,
    'function-name-case': 'lower',
    'selector-type-case': 'lower',
    'value-keyword-case': 'lower',
    'comment-whitespace-inside': 'always',
  },
};

/** Еще один варинат конфига
module.exports = {
  rules: {
    'color-no-invalid-hex': true,
    'value-keyword-case': ['lower', { camelCaseSvgKeywords: true }],
    'property-no-unknown': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'media-feature-name-no-unknown': true,
    'comment-no-empty': true,
    'no-descending-specificity': true,
    'no-duplicate-selectors': true,
    'no-invalid-position-at-import-rule': true,
    'alpha-value-notation': 'number',
    'color-function-notation': 'modern',
    'color-hex-length': 'short',
    'length-zero-no-unit': true,
    'function-url-quotes': 'never',
    'import-notation': 'url',
    'shorthand-property-no-redundant-values': true,
    'declaration-no-important': true,
    'declaration-block-single-line-max-declarations': 1,
    'no-unknown-animations': true,
    'selector-type-case': 'lower',
    'rule-empty-line-before': 'always',
    'at-rule-empty-line-before': 'always',
    'selector-class-pattern': null,
    'font-family-name-quotes': 'always-where-recommended',
  },
};
 */
